# Generated by Django 5.2.1 on 2025-05-08 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('learner', 'Learner'), ('trainer', 'Trainer'), ('admin', 'Admin')], default='learner', max_length=155),
        ),
    ]
