# Generated by Django 5.2.1 on 2025-06-11 06:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_trainerprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainerprofile',
            name='user',
            field=models.OneToOneField(limit_choices_to={'role': 'trainer'}, on_delete=django.db.models.deletion.CASCADE, related_name='trainer_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
