# Generated by Django 5.2.1 on 2025-05-13 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_user_email_verified'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='email_verified',
            new_name='is_email_verified',
        ),
    ]
