# Generated by Django 5.2.1 on 2025-05-13 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_rename_email_verified_user_is_email_verified'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_email_verified',
            new_name='isemail_verified',
        ),
    ]
