# Generated by Django 5.2.1 on 2025-05-13 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_rename_is_email_verified_user_isemail_verified'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='isemail_verified',
            new_name='is_email_verified',
        ),
    ]
