# Generated by Django 5.2.1 on 2025-05-15 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_remove_passwordresetotp_is_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='passwordresetotp',
            name='is_expired',
            field=models.BooleanField(default=False),
        ),
    ]
