# Generated by Django 5.2.1 on 2025-05-15 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_passwordresetotp_is_expired'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passwordresetotp',
            name='is_expired',
        ),
    ]
