# Generated by Django 5.2.1 on 2025-07-04 13:59

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Room_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('user1', models.IntegerField()),
                ('user2', models.IntegerField()),
            ],
            options={
                'unique_together': {('user1', 'user2')},
            },
        ),
    ]
