# Generated by Django 5.2.1 on 2025-07-06 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatroom',
            old_name='Room_id',
            new_name='room_id',
        ),
    ]
