# Generated by Django 5.2.1 on 2025-05-26 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('trainer', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('video', models.FileField(blank=True, null=True, upload_to='course_videos/')),
                ('is_published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.IntegerField()),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ManyToManyField(to='course.course')),
            ],
        ),
    ]
