# Generated by Django 5.2.1 on 2025-05-30 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_remove_enrollment_course_coursevideo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='video',
        ),
    ]
