# Generated by Django 5.2.1 on 2025-06-09 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_remove_course_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='thumbnails/'),
        ),
    ]
