# Generated by Django 5.2.1 on 2025-06-09 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_course_course_thumbnail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='course_thumbnail',
            new_name='thumbnail',
        ),
    ]
