# Generated by Django 5.2.1 on 2025-06-17 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_rename_course_thumbnail_course_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='is_trending',
            field=models.BooleanField(default=False),
        ),
    ]
