# Generated by Django 5.2.1 on 2025-06-18 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_course_is_trending'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coursevideo',
            old_name='video',
            new_name='video_url',
        ),
    ]
