# Generated by Django 5.2.1 on 2025-06-18 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0008_rename_video_coursevideo_video_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='topics',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
