# Generated by Django 5.2.1 on 2025-06-19 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0009_course_topics'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='categorypyth',
            field=models.CharField(choices=[('programming', 'Programming'), ('design', 'Design'), ('marketing', 'Marketing'), ('business', 'Business'), ('data', 'Data Science'), ('personal_dev', 'Personal Development')], max_length=355, null=True),
        ),
    ]
